name: gdiptv
on:
  schedule:
    - cron: '0 9,21 * * *'
  push:
    branches:
      - main
      
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.SUPER_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 20
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install opencv-python requests 
      - name: Run gengxinip
        run: python ${{ github.workspace }}/gdiptv.py
     
      - name: Commit results
        run: |
          git config --local user.email "bsexing@gmail.com"
          git config --local user.name "xiaotan8"
          if [ -n "$(git status --porcelain)" ]; then
            git add *.txt *.m3u
            git commit -m "Automatic update"
            git push -f
          else
            echo "No changes detected, skipping commit."
          fi
